# Generated by Django 5.0.2 on 2025-05-20 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0004_remove_maestros_edad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('horario_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=250, null=True)),
                ('publico_objetivo', models.TextField(blank=True, help_text="JSON o lista de valores: ['ESTUDIANTES','PROFESORES','PUBLICO_GENERAL']", null=True)),
                ('programa_educativo', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
