# Generated by Django 5.0.2 on 2025-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_alter_eventos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='horario_fin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='horario_inicio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
